config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#delete'
  resources :posts,     only: [:new, :create, :index]
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  #before_create { remember }
  validates :username,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  #def User.digest(string)
  #  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  #                                                BCrypt::Engine.cost
  #  BCrypt::Password.create(string, cost: cost)
  #end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = SecureRandom.urlsafe_base64
    #update_attribute(:remember_digest, User.digest(remember_token))
    update_attribute(:remember_digest, Digest::SHA1.hexdigest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    #BCrypt::Password.new(remember_digest).is_password?(remember_token)
    self.remember_digest == Digest::SHA1.hexdigest(remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in"
      redirect_to login_url
    end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def new
  end

  def create
    @micropost = current_user.posts.build(post_params)
    if @micropost.save
      flash[:success] = "Post created"
      redirect_to posts_url
    else
      flash[:danger] = "Invalid post"
      render 'new'
    end
  end

  private
    def post_params
      params.require(:post).permit(:content)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      flash[:success] = "welcome"
      redirect_back_or posts_url
    else
      flash.now[:danger] = "Invalid email or password"
      render 'new'
    end
  end

  def delete
    sign_out
    redirect_to login_path
  end

  #private
  #  def user_params
  #    params.require(:user).permit(:email, :password)
  #  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User created"
      sign_in @user
      redirect_to posts_path
    else
      flash[:danger] = "Error"
      render 'new'
    end
  end

  private
   def user_params
     params.require(:user).permit(:username, :email, :password,
                                  :password_confirmation)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    #session[:user_id] = user.id
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
    current_user=(user)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    #if session[:user_id]
    #  @current_user ||= User.find_by(id: session[:user_id])
    #els
    @current_user ||= retrieve
  end

  def retrieve
    if cookies.signed[:user_id]
      user = User.find_by(id: cookies.signed[:user_id])
      if user && user.authenticated?(cookies[:remember_token])
        session[:user_id] = user.id
        @current_user = user
      end
    end
  end


  def sign_out
    #session.delete(:user_id)
    @current_user = nil
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def logged_in?
    !current_user.nil?
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "Members only App", login_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Posts", posts_path %></li>
          <% if logged_in? %>
        	<li><%= link_to "Log out", logout_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |name, msg| %>
       <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
       <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/posts/_post.html.erb
<li id="micropost-<%= post.id %>">
  <% if logged_in? %>
    <span class="user"><%= post.user.username %></span>
  <% end %>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
</li>

app/views/posts/index.html.erb
<h1>All posts</h1>

<div><%= link_to "Create New Post", new_post_path, class: "btn btn-primary", style: "float: right;" %></div>

<div>
<ul class="microposts">
  <%= render @posts %>
</ul>
</div>

app/views/posts/new.html.erb
<h1>Post</h1>

<%= form_for(:post, url: posts_path) do |f| %>
  <%= f.label :content %><br>
  <%= f.text_area :content,  :cols => "5", :rows => "5", class: 'form-control' %><br>

  <%= f.submit "submit", class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>